GO
USE ClinicaStomatologica
GO


--dirty reads (1)
BEGIN TRAN
UPDATE Serviciu SET Pret=170 WHERE Denumire='Consultatie'
WAITFOR DELAY '00:00:10'
ROLLBACK TRAN


--rezolvare
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Serviciu
COMMIT TRAN


--non-repetable reads (1)
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
BEGIN TRAN
SELECT * FROM Serviciu
WAITFOR DELAY '00:00:09'
SELECT * FROM Serviciu
COMMIT TRAN	

--rezolvare
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Serviciu
WAITFOR DELAY '00:00:09'
SELECT * FROM Serviciu
COMMIT TRAN


--phantom reads(1)
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Serviciu WHERE Pret BETWEEN 200 AND 300;
WAITFOR DELAY '00:00:09'
SELECT * FROM Serviciu WHERE Pret BETWEEN 200 AND 300;
COMMIT TRAN

--rezolvare
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
SELECT * FROM Serviciu WHERE Pret BETWEEN 200 AND 300;
WAITFOR DELAY '00:00:09'
SELECT * FROM Serviciu WHERE Pret BETWEEN 200 AND 300;
COMMIT TRAN


--deadlock(1)
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
UPDATE Medicament SET Pret=30 WHERE Denumire='Nurofen'
WAITFOR DELAY '00:00:10'
UPDATE Serviciu SET Denumire='Activare' where Denumire='Activare aparat fix'
COMMIT TRAN

--rezolvare
SET DEADLOCK_PRIORITY HIGH
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE
BEGIN TRAN
UPDATE Serviciu SET Denumire='Activare' where Denumire='Activare aparat fix'
WAITFOR DELAY '00:00:10'
UPDATE Medicament SET Pret=30 WHERE Denumire='Nurofen'
COMMIT TRAN



